services:
  app:
    build: .
    image: cross-chain-mint
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - prisma-db:/usr/src/app/prisma/
    environment:
      NODE_ENV: development

volumes:
  prisma-db:
